### ISSUE TITLE
Release 4.3.2

### ISSUE THREAD

**Issue by perigoso** [STMicroelectronics/cmsis_device_f1#2]
A commit named v4.3.2 was push but no proper release was made, could someone make a formal release for 4.3.2

**Comment by RKOUSTM** [comment]
Hi @perigoso,

Thank you for this report. Tag ``v4.3.2`` is now available in our ``cmsis_device_f1`` repository.

Please allow me to close this thread. Thank you again for having reported this point. 

With regards,
