### ISSUE TITLE
The default clock speed for all F1xx chips is wrong

### ISSUE THREAD

**Issue by jcw** [STMicroelectronics/cmsis_device_f1#3]
**Describe the set-up**
 * Any F1-based board, e.g. Nucleo-F103RB
 * I'm using PlatformIO (https://platformio.org), which uses `arm-eabi-none-gcc` and an unmodified CMSIS install.

**Describe the bug**
The default clock speed for all F1xx chips is wrong. It is set to 16000000, but should be 8000000, see
https://github.com/STMicroelectronics/cmsis_device_f1/blob/master/Source/Templates/system_stm32f1xx.c#L141

**How To Reproduce**
1. Any CMSIS-based build which does not reconfigure the clock tree will have the wrong `SystemCoreClock` value.
This will cause baudrate calculations to be wrong, for example.

2. The modules that you suspect to be the cause of the problem (Driver, BSP, MW ...)
`Source/Templates/system_stm32f1xx.c`, line 141

4. The use case that generates the problem
See 1.

6. How we can reproduce the problem
See 1.

**Additional context**
This bug was first reported here: https://github.com/platformio/platform-ststm32/issues/698

**Screenshots**
N/A.

**Comment by ALABSTM** [comment]
Hello @jcw, 

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With regards,

**Comment by TOUNSTM** [comment]
ST Internal Reference: 155856

**Comment by TOUNSTM** [comment]
Fixed in commit 1d9e5f4f580ea970bdc512252ff0edf10481b5b2

**Comment by jcw** [comment]
Thank you.
