### ISSUE TITLE
License problem of linker script

### ISSUE THREAD

**Issue by XuHg-zjcn** [STMicroelectronics/cmsis_device_f1#4]
I'm building a linux toolchain for STM32, but I found some file's license does not permitted distribution it, they are in directory `Source/Templates/gcc/linker`

These files with this license:
>  (c)Copyright Ac6.
>  You may use this file as-is or modify it according to the needs of your
>  project. Distribution of this file (unmodified or modified) is not
>  permitted. Ac6 permit registered System Workbench for MCU users the
>  rights to distribute the assembled, compiled & linked contents of this
>  file as part of an application binary file, provided that it is built
>  using the System Workbench for MCU toolchain.

Can you provide a free/open-source license or replace it to free/open-source licensed linker script.

**Comment by RJMSTM** [comment]
Hello @XuHg-zjcn ,

Thank you for your contribution. You are absolutely right about this point. Actually, the point you raised has already been dealt and fixed internally. We cannot share a date for the moment, but we will do our best to have such a global update deployed and released soon. We count on your patience.

Thank you again for your contribution. We are looking forward to reading from you again.

With regards,

**Comment by XuHg-zjcn** [comment]
Thanks your reply

I wrote [a linker script](https://github.com/XuHg-zjcn/xx32_hal_libre/blob/main/device/STM32F103/LDScript/stm32f103x8.ld) try to instead, but it can't instead successful, build errors happened after instead for some programs.
I think your company maybe can offer better alternatives with a compatibility license to this repo, so was report the issue to get help.

Your said release after global update, I'm looking forward to your update.

**Comment by RJMSTM** [comment]
ST Internal Reference: 179067
